version: '3.10'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8001'
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb:10.4 # mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORT: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
